version: '3.7'

volumes:
    prometheus_data: {}
networks:
  lesson-01:
services:
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./setting/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - lesson-01
    restart: always
